title: convospot.io - simple intelligent communication
header:
  menu_name: 'MENU'
author:
  name: Homer Quan
  email: 'web@convospot.io'
metadata:
    description: 'Convospot provides chatbot with knowledge and actions'

