title: convospot.io
header:
  logo: 'user/themes/convospot/assets/imgs/logo.png'
  menu_name: 'MENU'
author:
  name: Homer Quan
  email: 'web@convospot.io'
metadata:
    description: 'Simple and intelligent communication by chatbots with knowledge and actions'
    keywords: 'chatbot, communication, ai, marketing automation'

